# Generated by Django 4.2 on 2025-11-06 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'charge'), (2, 'purchase'), (3, 'transfer')], default=1),
        ),
    ]
