# Generated by Django 4.2 on 2025-10-26 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producttype',
            name='title',
            field=models.CharField(blank=True, max_length=32, verbose_name='this for alternative of (title)'),
        ),
    ]
