# Generated by Django 4.2 on 2025-10-27 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_rename_produt_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='Category_id',
            new_name='category_id',
        ),
    ]
