# Generated by Django 4.2 on 2025-10-29 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_productattributevalue'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productattributevalue',
            name='Product',
        ),
    ]
